language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - xorg-dev

dist: xenial

before_script:
  - git clone --depth 1 https://github.com/bkaradzic/bx ../bx
  - git clone --depth 1 https://github.com/hugoam/bimg ../bimg
  - git clone --depth 1 https://github.com/hugoam/bgfx ../bgfx
  - git clone --depth 1 https://github.com/hugoam/two ../two

matrix:
  include:
    - os: linux
      compiler: gcc
      script:
        - bin/linux/genie --compile-only --gcc=linux-gcc-8 gmake
        - cd build/projects/gmake-linux-gcc-8
        - time make config=debug64
    - os: linux
      compiler: clang
      script:
        - bin/linux/genie --compile-only --gcc=linux-clang gmake
        - cd build/projects/gmake-linux-clang
        - time make config=debug64
    - os: osx
      compiler: clang
      osx_image: xcode10
      script:
        - bin/darwin/genie --compile-only --gcc=osx gmake
        - cd build/projects/gmake-osx
        - time make config=debug64
    - os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - bin/windows/genie --compile-only vs2017
        - cd build/projects/vs2017
        - export PATH=$MSBUILD_PATH:$PATH
        - MSBuild.exe two.sln //m //nologo //verbosity:minimal //p:Configuration=Debug //p:Platform=x64

